# Generated by Django 5.0.4 on 2024-04-23 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='group',
            new_name='group_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='fullname',
        ),
    ]
