# Generated by Django 5.0.4 on 2024-04-24 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_perdiod_period_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='fullname',
        ),
        migrations.AddField(
            model_name='manager',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.student'),
            preserve_default=False,
        ),
    ]
