# Generated by Django 5.0.4 on 2024-04-25 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_manager_fullname_manager_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skipping',
            old_name='ivalid_skipping',
            new_name='invalid_skipping',
        ),
    ]
