# Generated by Django 5.0.4 on 2024-05-01 12:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_ivalid_skipping_skipping_invalid_skipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='date',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='skipping',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
