# Generated by Django 5.0.4 on 2024-05-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_period_date_alter_skipping_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skipping',
            name='date',
            field=models.CharField(max_length=30),
        ),
    ]
